import { ParsedData } from "../types";
import { EXPECTED_SCHEMA } from "./expectedSchema";

export const PARSED_DATA: ParsedData = [
  {
    schema: EXPECTED_SCHEMA,
    data: [
      {
        balanceDollars: 3523.41,
        age: 34,
        eyeColor: "brown",
        firstName: "Chan",
        lastName: "Guerrero",
        gender: "male",
        email: "changuerrero@diginetic.com",
        latitude: -65.100845,
        longitude: 175.975673,
      },
      {
        balanceDollars: 1730.84,
        age: 32,
        eyeColor: "blue",
        firstName: "Rosario",
        lastName: "Flynn",
        gender: "female",
        email: "rosarioflynn@diginetic.com",
        latitude: 7.341149,
        longitude: 53.534203,
      },
      {
        balanceDollars: 3858.8,
        age: 29,
        eyeColor: "blue",
        firstName: "Brewer",
        lastName: "Ruiz",
        gender: "male",
        email: "brewerruiz@diginetic.com",
        latitude: -62.191975,
        longitude: -173.372846,
      },
      {
        balanceDollars: 1401.67,
        age: 36,
        eyeColor: "blue",
        firstName: "Aline",
        lastName: "Owens",
        gender: "female",
        email: "alineowens@diginetic.com",
        latitude: 50.404881,
        longitude: 111.373872,
      },
      {
        balanceDollars: 1577.35,
        age: 24,
        eyeColor: "brown",
        firstName: "Rojas",
        lastName: "Le",
        gender: "male",
        email: "rojasle@diginetic.com",
        latitude: -57.872467,
        longitude: -73.996195,
      },
      {
        balanceDollars: 2954.7,
        age: 25,
        eyeColor: "blue",
        firstName: "Avis",
        lastName: "Gordon",
        gender: "female",
        email: "avisgordon@diginetic.com",
        latitude: -7.170359,
        longitude: -103.168995,
      },
      {
        balanceDollars: 1315.04,
        age: 33,
        eyeColor: "blue",
        firstName: "Rogers",
        lastName: "Ford",
        gender: "male",
        email: "rogersford@diginetic.com",
        latitude: -63.577798,
        longitude: -0.675456,
      },
      {
        balanceDollars: 1855.58,
        age: 38,
        eyeColor: "brown",
        firstName: "Kelly",
        lastName: "Simpson",
        gender: "male",
        email: "kellysimpson@diginetic.com",
        latitude: -6.218272,
        longitude: -97.198928,
      },
      {
        balanceDollars: 1057.83,
        age: 27,
        eyeColor: "green",
        firstName: "Mercer",
        lastName: "Mejia",
        gender: "male",
        email: "mercermejia@diginetic.com",
        latitude: -42.385266,
        longitude: -157.254064,
      },
      {
        balanceDollars: 2760.45,
        age: 27,
        eyeColor: "brown",
        firstName: "Levine",
        lastName: "Travis",
        gender: "male",
        email: "levinetravis@diginetic.com",
        latitude: -37.987614,
        longitude: 106.14155,
      },
      {
        balanceDollars: 1205.73,
        age: 21,
        eyeColor: "brown",
        firstName: "Jerri",
        lastName: "Herman",
        gender: "female",
        email: "jerriherman@diginetic.com",
        latitude: 85.65643,
        longitude: 15.387216,
      },
      {
        balanceDollars: 1574.11,
        age: 39,
        eyeColor: "brown",
        firstName: "Whitney",
        lastName: "Holt",
        gender: "female",
        email: "whitneyholt@diginetic.com",
        latitude: -1.313761,
        longitude: 109.435756,
      },
      {
        balanceDollars: 2935.66,
        age: 38,
        eyeColor: "brown",
        firstName: "Goldie",
        lastName: "Lopez",
        gender: "female",
        email: "goldielopez@diginetic.com",
        latitude: 52.267298,
        longitude: 145.719877,
      },
      {
        balanceDollars: 3275.72,
        age: 20,
        eyeColor: "green",
        firstName: "Celina",
        lastName: "Branch",
        gender: "female",
        email: "celinabranch@diginetic.com",
        latitude: 25.580002,
        longitude: 12.286585,
      },
      {
        balanceDollars: 2839.84,
        age: 24,
        eyeColor: "brown",
        firstName: "Henson",
        lastName: "Russell",
        gender: "male",
        email: "hensonrussell@diginetic.com",
        latitude: -9.978004,
        longitude: -37.282375,
      },
      {
        balanceDollars: 2094.23,
        age: 33,
        eyeColor: "green",
        firstName: "Valenzuela",
        lastName: "Morales",
        gender: "male",
        email: "valenzuelamorales@diginetic.com",
        latitude: 21.332013,
        longitude: -89.514579,
      },
      {
        balanceDollars: 1279.33,
        age: 36,
        eyeColor: "blue",
        firstName: "Flossie",
        lastName: "Harrington",
        gender: "female",
        email: "flossieharrington@diginetic.com",
        latitude: 82.714816,
        longitude: -98.863611,
      },
      {
        balanceDollars: 3504.87,
        age: 25,
        eyeColor: "green",
        firstName: "Violet",
        lastName: "Rice",
        gender: "female",
        email: "violetrice@diginetic.com",
        latitude: 16.511898,
        longitude: -59.977725,
      },
      {
        balanceDollars: 1303.49,
        age: 32,
        eyeColor: "green",
        firstName: "Oneal",
        lastName: "Camacho",
        gender: "male",
        email: "onealcamacho@diginetic.com",
        latitude: -29.347048,
        longitude: 81.005717,
      },
      {
        balanceDollars: 3289.64,
        age: 25,
        eyeColor: "green",
        firstName: "Vera",
        lastName: "Clemons",
        gender: "female",
        email: "veraclemons@diginetic.com",
        latitude: 60.059796,
        longitude: -28.4383,
      },
      {
        balanceDollars: 1534.62,
        age: 36,
        eyeColor: "blue",
        firstName: "Rosemarie",
        lastName: "Noel",
        gender: "female",
        email: "rosemarienoel@diginetic.com",
        latitude: 45.463863,
        longitude: -23.229058,
      },
      {
        balanceDollars: 3152.27,
        age: 22,
        eyeColor: "brown",
        firstName: "Debora",
        lastName: "Boone",
        gender: "female",
        email: "deboraboone@diginetic.com",
        latitude: 44.390079,
        longitude: -83.309253,
      },
      {
        balanceDollars: 3018.07,
        age: 25,
        eyeColor: "brown",
        firstName: "Harding",
        lastName: "Hanson",
        gender: "male",
        email: "hardinghanson@diginetic.com",
        latitude: 62.593675,
        longitude: -30.089868,
      },
    ],
  },
];
