import { OperatorType, TokenType } from "../enums";
import { ParsedQuery, ParsedTable, Token, WhereCondition } from "../types";
import { EXPECTED_SCHEMA } from "./expectedSchema";

export type TestQuery = {
  input: string;
  expectedQuery: ParsedQuery;
  expectedLengthOfAllRows: number | null;
  expectedTokens?: Token[];
  expectedWhere?: WhereCondition;
  expectedFilteredRows?: ParsedTable;
  shouldFailWithError?: string;
};

export const TEST_QUERIES: TestQuery[] = [
  {
    input:
      ` SELECT  "firstName","lastName", "age", "eyeColor" ` +
      ` FROM  user  WHERE ` +
      ` age  > 30;`,
    expectedQuery: {
      select: ['"firstName"', '"lastName"', '"age"', '"eyeColor"'],
      from: "user",
      whereStr: "age  > 30",
    },
    expectedLengthOfAllRows: 23,
    expectedTokens: [
      { type: TokenType.STRING, value: "age" },
      { type: TokenType.OPERATOR, value: OperatorType.GREATER_THAN },
      { type: TokenType.NUMBER, value: 30 },
    ],
    expectedWhere: {
      left: "age",
      operator: OperatorType.GREATER_THAN,
      right: 30,
      discriminator: "binary",
    },
    expectedFilteredRows: {
      schema: EXPECTED_SCHEMA,
      data: [
        {
          balanceDollars: 3523.41,
          age: 34,
          eyeColor: "brown",
          firstName: "Chan",
          lastName: "Guerrero",
          gender: "male",
          email: "changuerrero@diginetic.com",
          latitude: -65.100845,
          longitude: 175.975673,
        },
        {
          balanceDollars: 1730.84,
          age: 32,
          eyeColor: "blue",
          firstName: "Rosario",
          lastName: "Flynn",
          gender: "female",
          email: "rosarioflynn@diginetic.com",
          latitude: 7.341149,
          longitude: 53.534203,
        },
        {
          balanceDollars: 1401.67,
          age: 36,
          eyeColor: "blue",
          firstName: "Aline",
          lastName: "Owens",
          gender: "female",
          email: "alineowens@diginetic.com",
          latitude: 50.404881,
          longitude: 111.373872,
        },
        {
          balanceDollars: 1315.04,
          age: 33,
          eyeColor: "blue",
          firstName: "Rogers",
          lastName: "Ford",
          gender: "male",
          email: "rogersford@diginetic.com",
          latitude: -63.577798,
          longitude: -0.675456,
        },
        {
          balanceDollars: 1855.58,
          age: 38,
          eyeColor: "brown",
          firstName: "Kelly",
          lastName: "Simpson",
          gender: "male",
          email: "kellysimpson@diginetic.com",
          latitude: -6.218272,
          longitude: -97.198928,
        },
        {
          balanceDollars: 1574.11,
          age: 39,
          eyeColor: "brown",
          firstName: "Whitney",
          lastName: "Holt",
          gender: "female",
          email: "whitneyholt@diginetic.com",
          latitude: -1.313761,
          longitude: 109.435756,
        },
        {
          balanceDollars: 2935.66,
          age: 38,
          eyeColor: "brown",
          firstName: "Goldie",
          lastName: "Lopez",
          gender: "female",
          email: "goldielopez@diginetic.com",
          latitude: 52.267298,
          longitude: 145.719877,
        },
        {
          balanceDollars: 2094.23,
          age: 33,
          eyeColor: "green",
          firstName: "Valenzuela",
          lastName: "Morales",
          gender: "male",
          email: "valenzuelamorales@diginetic.com",
          latitude: 21.332013,
          longitude: -89.514579,
        },
        {
          balanceDollars: 1279.33,
          age: 36,
          eyeColor: "blue",
          firstName: "Flossie",
          lastName: "Harrington",
          gender: "female",
          email: "flossieharrington@diginetic.com",
          latitude: 82.714816,
          longitude: -98.863611,
        },
        {
          balanceDollars: 1303.49,
          age: 32,
          eyeColor: "green",
          firstName: "Oneal",
          lastName: "Camacho",
          gender: "male",
          email: "onealcamacho@diginetic.com",
          latitude: -29.347048,
          longitude: 81.005717,
        },
        {
          balanceDollars: 1534.62,
          age: 36,
          eyeColor: "blue",
          firstName: "Rosemarie",
          lastName: "Noel",
          gender: "female",
          email: "rosemarienoel@diginetic.com",
          latitude: 45.463863,
          longitude: -23.229058,
        },
      ],
    },
  },
  {
    input:
      ` SELECT  "firstName","lastName", "age", "eyeColor" ` +
      ` FROM  user  WHERE ` +
      ` age  > 30 OR ("eyeColor" = "blue" AND gender != "male");`,
    expectedQuery: {
      select: ['"firstName"', '"lastName"', '"age"', '"eyeColor"'],
      from: "user",
      whereStr: 'age  > 30 OR ("eyeColor" = "blue" AND gender != "male")',
    },
    expectedLengthOfAllRows: 23,
    expectedTokens: [
      { type: TokenType.STRING, value: "age" },
      { type: TokenType.OPERATOR, value: OperatorType.GREATER_THAN },
      { type: TokenType.NUMBER, value: 30 },
      { type: TokenType.OPERATOR, value: OperatorType.OR },
      { type: TokenType.OPERATOR, value: OperatorType.LEFT_PAREN },
      { type: TokenType.STRING, value: "eyeColor" },
      { type: TokenType.OPERATOR, value: OperatorType.EQUAL },
      { type: TokenType.STRING, value: "blue" },
      { type: TokenType.OPERATOR, value: OperatorType.AND },
      { type: TokenType.STRING, value: "gender" },
      { type: TokenType.OPERATOR, value: OperatorType.NOT_EQUAL },
      { type: TokenType.STRING, value: "male" },
      { type: TokenType.OPERATOR, value: OperatorType.RIGHT_PAREN },
    ],
    expectedWhere: {
      left: {
        left: "age",
        operator: OperatorType.GREATER_THAN,
        right: 30,
        discriminator: "binary",
      },
      operator: OperatorType.OR,
      right: {
        left: {
          left: "eyeColor",
          operator: OperatorType.EQUAL,
          right: "blue",
          discriminator: "binary",
        },
        operator: OperatorType.AND,
        right: {
          left: "gender",
          operator: OperatorType.NOT_EQUAL,
          right: "male",
          discriminator: "binary",
        },
        discriminator: "group",
      },
      discriminator: "group",
    },
    expectedFilteredRows: {
      schema: EXPECTED_SCHEMA,
      data: [
        {
          balanceDollars: 3523.41,
          age: 34,
          eyeColor: "brown",
          firstName: "Chan",
          lastName: "Guerrero",
          gender: "male",
          email: "changuerrero@diginetic.com",
          latitude: -65.100845,
          longitude: 175.975673,
        },
        {
          balanceDollars: 1730.84,
          age: 32,
          eyeColor: "blue",
          firstName: "Rosario",
          lastName: "Flynn",
          gender: "female",
          email: "rosarioflynn@diginetic.com",
          latitude: 7.341149,
          longitude: 53.534203,
        },
        {
          balanceDollars: 1401.67,
          age: 36,
          eyeColor: "blue",
          firstName: "Aline",
          lastName: "Owens",
          gender: "female",
          email: "alineowens@diginetic.com",
          latitude: 50.404881,
          longitude: 111.373872,
        },
        {
          balanceDollars: 2954.7,
          age: 25,
          eyeColor: "blue",
          firstName: "Avis",
          lastName: "Gordon",
          gender: "female",
          email: "avisgordon@diginetic.com",
          latitude: -7.170359,
          longitude: -103.168995,
        },
        {
          balanceDollars: 1315.04,
          age: 33,
          eyeColor: "blue",
          firstName: "Rogers",
          lastName: "Ford",
          gender: "male",
          email: "rogersford@diginetic.com",
          latitude: -63.577798,
          longitude: -0.675456,
        },
        {
          balanceDollars: 1855.58,
          age: 38,
          eyeColor: "brown",
          firstName: "Kelly",
          lastName: "Simpson",
          gender: "male",
          email: "kellysimpson@diginetic.com",
          latitude: -6.218272,
          longitude: -97.198928,
        },
        {
          balanceDollars: 1574.11,
          age: 39,
          eyeColor: "brown",
          firstName: "Whitney",
          lastName: "Holt",
          gender: "female",
          email: "whitneyholt@diginetic.com",
          latitude: -1.313761,
          longitude: 109.435756,
        },
        {
          balanceDollars: 2935.66,
          age: 38,
          eyeColor: "brown",
          firstName: "Goldie",
          lastName: "Lopez",
          gender: "female",
          email: "goldielopez@diginetic.com",
          latitude: 52.267298,
          longitude: 145.719877,
        },
        {
          balanceDollars: 2094.23,
          age: 33,
          eyeColor: "green",
          firstName: "Valenzuela",
          lastName: "Morales",
          gender: "male",
          email: "valenzuelamorales@diginetic.com",
          latitude: 21.332013,
          longitude: -89.514579,
        },
        {
          balanceDollars: 1279.33,
          age: 36,
          eyeColor: "blue",
          firstName: "Flossie",
          lastName: "Harrington",
          gender: "female",
          email: "flossieharrington@diginetic.com",
          latitude: 82.714816,
          longitude: -98.863611,
        },
        {
          balanceDollars: 1303.49,
          age: 32,
          eyeColor: "green",
          firstName: "Oneal",
          lastName: "Camacho",
          gender: "male",
          email: "onealcamacho@diginetic.com",
          latitude: -29.347048,
          longitude: 81.005717,
        },
        {
          balanceDollars: 1534.62,
          age: 36,
          eyeColor: "blue",
          firstName: "Rosemarie",
          lastName: "Noel",
          gender: "female",
          email: "rosemarienoel@diginetic.com",
          latitude: 45.463863,
          longitude: -23.229058,
        },
      ],
    },
  },
  {
    input:
      ` SELECT  "firstName","lastName", "age", "eyeColor" ` +
      ` FROM  user  WHERE ` +
      ` (age  > 30) OR ("eyeColor" = "blue" AND gender != "male");`,
    expectedQuery: {
      select: ['"firstName"', '"lastName"', '"age"', '"eyeColor"'],
      from: "user",
      whereStr: '(age  > 30) OR ("eyeColor" = "blue" AND gender != "male")',
    },
    expectedLengthOfAllRows: 23,
    expectedTokens: [
      { type: TokenType.OPERATOR, value: OperatorType.LEFT_PAREN },
      { type: TokenType.STRING, value: "age" },
      { type: TokenType.OPERATOR, value: OperatorType.GREATER_THAN },
      { type: TokenType.NUMBER, value: 30 },
      { type: TokenType.OPERATOR, value: OperatorType.RIGHT_PAREN },
      { type: TokenType.OPERATOR, value: OperatorType.OR },
      { type: TokenType.OPERATOR, value: OperatorType.LEFT_PAREN },
      { type: TokenType.STRING, value: "eyeColor" },
      { type: TokenType.OPERATOR, value: OperatorType.EQUAL },
      { type: TokenType.STRING, value: "blue" },
      { type: TokenType.OPERATOR, value: OperatorType.AND },
      { type: TokenType.STRING, value: "gender" },
      { type: TokenType.OPERATOR, value: OperatorType.NOT_EQUAL },
      { type: TokenType.STRING, value: "male" },
      { type: TokenType.OPERATOR, value: OperatorType.RIGHT_PAREN },
    ],
    expectedWhere: {
      left: {
        left: "age",
        operator: OperatorType.GREATER_THAN,
        right: 30,
        discriminator: "binary",
      },
      operator: OperatorType.OR,
      right: {
        left: {
          left: "eyeColor",
          operator: OperatorType.EQUAL,
          right: "blue",
          discriminator: "binary",
        },
        operator: OperatorType.AND,
        right: {
          left: "gender",
          operator: OperatorType.NOT_EQUAL,
          right: "male",
          discriminator: "binary",
        },
        discriminator: "group",
      },
      discriminator: "group",
    },
    expectedFilteredRows: {
      schema: EXPECTED_SCHEMA,
      data: [
        {
          balanceDollars: 3523.41,
          age: 34,
          eyeColor: "brown",
          firstName: "Chan",
          lastName: "Guerrero",
          gender: "male",
          email: "changuerrero@diginetic.com",
          latitude: -65.100845,
          longitude: 175.975673,
        },
        {
          balanceDollars: 1730.84,
          age: 32,
          eyeColor: "blue",
          firstName: "Rosario",
          lastName: "Flynn",
          gender: "female",
          email: "rosarioflynn@diginetic.com",
          latitude: 7.341149,
          longitude: 53.534203,
        },
        {
          balanceDollars: 1401.67,
          age: 36,
          eyeColor: "blue",
          firstName: "Aline",
          lastName: "Owens",
          gender: "female",
          email: "alineowens@diginetic.com",
          latitude: 50.404881,
          longitude: 111.373872,
        },
        {
          balanceDollars: 2954.7,
          age: 25,
          eyeColor: "blue",
          firstName: "Avis",
          lastName: "Gordon",
          gender: "female",
          email: "avisgordon@diginetic.com",
          latitude: -7.170359,
          longitude: -103.168995,
        },
        {
          balanceDollars: 1315.04,
          age: 33,
          eyeColor: "blue",
          firstName: "Rogers",
          lastName: "Ford",
          gender: "male",
          email: "rogersford@diginetic.com",
          latitude: -63.577798,
          longitude: -0.675456,
        },
        {
          balanceDollars: 1855.58,
          age: 38,
          eyeColor: "brown",
          firstName: "Kelly",
          lastName: "Simpson",
          gender: "male",
          email: "kellysimpson@diginetic.com",
          latitude: -6.218272,
          longitude: -97.198928,
        },
        {
          balanceDollars: 1574.11,
          age: 39,
          eyeColor: "brown",
          firstName: "Whitney",
          lastName: "Holt",
          gender: "female",
          email: "whitneyholt@diginetic.com",
          latitude: -1.313761,
          longitude: 109.435756,
        },
        {
          balanceDollars: 2935.66,
          age: 38,
          eyeColor: "brown",
          firstName: "Goldie",
          lastName: "Lopez",
          gender: "female",
          email: "goldielopez@diginetic.com",
          latitude: 52.267298,
          longitude: 145.719877,
        },
        {
          balanceDollars: 2094.23,
          age: 33,
          eyeColor: "green",
          firstName: "Valenzuela",
          lastName: "Morales",
          gender: "male",
          email: "valenzuelamorales@diginetic.com",
          latitude: 21.332013,
          longitude: -89.514579,
        },
        {
          balanceDollars: 1279.33,
          age: 36,
          eyeColor: "blue",
          firstName: "Flossie",
          lastName: "Harrington",
          gender: "female",
          email: "flossieharrington@diginetic.com",
          latitude: 82.714816,
          longitude: -98.863611,
        },
        {
          balanceDollars: 1303.49,
          age: 32,
          eyeColor: "green",
          firstName: "Oneal",
          lastName: "Camacho",
          gender: "male",
          email: "onealcamacho@diginetic.com",
          latitude: -29.347048,
          longitude: 81.005717,
        },
        {
          balanceDollars: 1534.62,
          age: 36,
          eyeColor: "blue",
          firstName: "Rosemarie",
          lastName: "Noel",
          gender: "female",
          email: "rosemarienoel@diginetic.com",
          latitude: 45.463863,
          longitude: -23.229058,
        },
      ],
    },
  },
  {
    input:
      ` SELECT  "firstName","lastName", "age", "eyeColor" ` +
      ` FROM  user  WHERE ` +
      ` ("age"  > 30) OR ("eyeColor" = "blue" AND gender != "male");`,
    expectedQuery: {
      select: ['"firstName"', '"lastName"', '"age"', '"eyeColor"'],
      from: "user",
      whereStr: '("age"  > 30) OR ("eyeColor" = "blue" AND gender != "male")',
    },
    expectedLengthOfAllRows: 23,
    expectedTokens: [
      { type: TokenType.OPERATOR, value: OperatorType.LEFT_PAREN },
      { type: TokenType.STRING, value: "age" },
      { type: TokenType.OPERATOR, value: OperatorType.GREATER_THAN },
      { type: TokenType.NUMBER, value: 30 },
      { type: TokenType.OPERATOR, value: OperatorType.RIGHT_PAREN },
      { type: TokenType.OPERATOR, value: OperatorType.OR },
      { type: TokenType.OPERATOR, value: OperatorType.LEFT_PAREN },
      { type: TokenType.STRING, value: "eyeColor" },
      { type: TokenType.OPERATOR, value: OperatorType.EQUAL },
      { type: TokenType.STRING, value: "blue" },
      { type: TokenType.OPERATOR, value: OperatorType.AND },
      { type: TokenType.STRING, value: "gender" },
      { type: TokenType.OPERATOR, value: OperatorType.NOT_EQUAL },
      { type: TokenType.STRING, value: "male" },
      { type: TokenType.OPERATOR, value: OperatorType.RIGHT_PAREN },
    ],
    expectedWhere: {
      left: {
        left: "age",
        operator: OperatorType.GREATER_THAN,
        right: 30,
        discriminator: "binary",
      },
      operator: OperatorType.OR,
      right: {
        left: {
          left: "eyeColor",
          operator: OperatorType.EQUAL,
          right: "blue",
          discriminator: "binary",
        },
        operator: OperatorType.AND,
        right: {
          left: "gender",
          operator: OperatorType.NOT_EQUAL,
          right: "male",
          discriminator: "binary",
        },
        discriminator: "group",
      },
      discriminator: "group",
    },
    expectedFilteredRows: {
      schema: EXPECTED_SCHEMA,
      data: [
        {
          balanceDollars: 3523.41,
          age: 34,
          eyeColor: "brown",
          firstName: "Chan",
          lastName: "Guerrero",
          gender: "male",
          email: "changuerrero@diginetic.com",
          latitude: -65.100845,
          longitude: 175.975673,
        },
        {
          balanceDollars: 1730.84,
          age: 32,
          eyeColor: "blue",
          firstName: "Rosario",
          lastName: "Flynn",
          gender: "female",
          email: "rosarioflynn@diginetic.com",
          latitude: 7.341149,
          longitude: 53.534203,
        },
        {
          balanceDollars: 1401.67,
          age: 36,
          eyeColor: "blue",
          firstName: "Aline",
          lastName: "Owens",
          gender: "female",
          email: "alineowens@diginetic.com",
          latitude: 50.404881,
          longitude: 111.373872,
        },
        {
          balanceDollars: 2954.7,
          age: 25,
          eyeColor: "blue",
          firstName: "Avis",
          lastName: "Gordon",
          gender: "female",
          email: "avisgordon@diginetic.com",
          latitude: -7.170359,
          longitude: -103.168995,
        },
        {
          balanceDollars: 1315.04,
          age: 33,
          eyeColor: "blue",
          firstName: "Rogers",
          lastName: "Ford",
          gender: "male",
          email: "rogersford@diginetic.com",
          latitude: -63.577798,
          longitude: -0.675456,
        },
        {
          balanceDollars: 1855.58,
          age: 38,
          eyeColor: "brown",
          firstName: "Kelly",
          lastName: "Simpson",
          gender: "male",
          email: "kellysimpson@diginetic.com",
          latitude: -6.218272,
          longitude: -97.198928,
        },
        {
          balanceDollars: 1574.11,
          age: 39,
          eyeColor: "brown",
          firstName: "Whitney",
          lastName: "Holt",
          gender: "female",
          email: "whitneyholt@diginetic.com",
          latitude: -1.313761,
          longitude: 109.435756,
        },
        {
          balanceDollars: 2935.66,
          age: 38,
          eyeColor: "brown",
          firstName: "Goldie",
          lastName: "Lopez",
          gender: "female",
          email: "goldielopez@diginetic.com",
          latitude: 52.267298,
          longitude: 145.719877,
        },
        {
          balanceDollars: 2094.23,
          age: 33,
          eyeColor: "green",
          firstName: "Valenzuela",
          lastName: "Morales",
          gender: "male",
          email: "valenzuelamorales@diginetic.com",
          latitude: 21.332013,
          longitude: -89.514579,
        },
        {
          balanceDollars: 1279.33,
          age: 36,
          eyeColor: "blue",
          firstName: "Flossie",
          lastName: "Harrington",
          gender: "female",
          email: "flossieharrington@diginetic.com",
          latitude: 82.714816,
          longitude: -98.863611,
        },
        {
          balanceDollars: 1303.49,
          age: 32,
          eyeColor: "green",
          firstName: "Oneal",
          lastName: "Camacho",
          gender: "male",
          email: "onealcamacho@diginetic.com",
          latitude: -29.347048,
          longitude: 81.005717,
        },
        {
          balanceDollars: 1534.62,
          age: 36,
          eyeColor: "blue",
          firstName: "Rosemarie",
          lastName: "Noel",
          gender: "female",
          email: "rosemarienoel@diginetic.com",
          latitude: 45.463863,
          longitude: -23.229058,
        },
      ],
    },
  },
  {
    input:
      ` SELECT  "firstName","lastName", "age", "eyeColor" ` +
      ` FROM  user  WHERE ` +
      ` ("eye Color" = "blue" AND gender != "female") ` +
      ` OR ("eyeColor" = "blue" AND gender != "male");`,
    expectedQuery: {
      select: ['"firstName"', '"lastName"', '"age"', '"eyeColor"'],
      from: "user",
      whereStr:
        '("eye Color" = "blue" AND gender != "female")  OR ("eyeColor" = "blue" AND gender != "male")',
    },
    expectedLengthOfAllRows: 23,
    expectedTokens: [
      { type: TokenType.OPERATOR, value: OperatorType.LEFT_PAREN },
      { type: TokenType.STRING, value: "eye Color" },
      { type: TokenType.OPERATOR, value: OperatorType.EQUAL },
      { type: TokenType.STRING, value: "blue" },
      { type: TokenType.OPERATOR, value: OperatorType.AND },
      { type: TokenType.STRING, value: "gender" },
      { type: TokenType.OPERATOR, value: OperatorType.NOT_EQUAL },
      { type: TokenType.STRING, value: "female" },
      { type: TokenType.OPERATOR, value: OperatorType.RIGHT_PAREN },
      { type: TokenType.OPERATOR, value: OperatorType.OR },
      { type: TokenType.OPERATOR, value: OperatorType.LEFT_PAREN },
      { type: TokenType.STRING, value: "eyeColor" },
      { type: TokenType.OPERATOR, value: OperatorType.EQUAL },
      { type: TokenType.STRING, value: "blue" },
      { type: TokenType.OPERATOR, value: OperatorType.AND },
      { type: TokenType.STRING, value: "gender" },
      { type: TokenType.OPERATOR, value: OperatorType.NOT_EQUAL },
      { type: TokenType.STRING, value: "male" },
      { type: TokenType.OPERATOR, value: OperatorType.RIGHT_PAREN },
    ],
    expectedWhere: {
      left: {
        left: {
          left: "eye Color",
          operator: OperatorType.EQUAL,
          right: "blue",
          discriminator: "binary",
        },
        operator: OperatorType.AND,
        right: {
          left: "gender",
          operator: OperatorType.NOT_EQUAL,
          right: "female",
          discriminator: "binary",
        },
        discriminator: "group",
      },
      operator: OperatorType.OR,
      right: {
        left: {
          left: "eyeColor",
          operator: OperatorType.EQUAL,
          right: "blue",
          discriminator: "binary",
        },
        operator: OperatorType.AND,
        right: {
          left: "gender",
          operator: OperatorType.NOT_EQUAL,
          right: "male",
          discriminator: "binary",
        },
        discriminator: "group",
      },
      discriminator: "group",
    },
    shouldFailWithError:
      "The left side of a binary condition (eye Color) must be a column key",
  },
  {
    input: ` SELECT  * ` + ` FROM  user;`,
    expectedLengthOfAllRows: 23,
    expectedQuery: {
      select: ["*"],
      from: "user",
    },
    expectedFilteredRows: {
      schema: EXPECTED_SCHEMA,
      data: [
        {
          balanceDollars: 3523.41,
          age: 34,
          eyeColor: "brown",
          firstName: "Chan",
          lastName: "Guerrero",
          gender: "male",
          email: "changuerrero@diginetic.com",
          latitude: -65.100845,
          longitude: 175.975673,
        },
        {
          balanceDollars: 1730.84,
          age: 32,
          eyeColor: "blue",
          firstName: "Rosario",
          lastName: "Flynn",
          gender: "female",
          email: "rosarioflynn@diginetic.com",
          latitude: 7.341149,
          longitude: 53.534203,
        },
        {
          balanceDollars: 1401.67,
          age: 36,
          eyeColor: "blue",
          firstName: "Aline",
          lastName: "Owens",
          gender: "female",
          email: "alineowens@diginetic.com",
          latitude: 50.404881,
          longitude: 111.373872,
        },
        {
          balanceDollars: 2954.7,
          age: 25,
          eyeColor: "blue",
          firstName: "Avis",
          lastName: "Gordon",
          gender: "female",
          email: "avisgordon@diginetic.com",
          latitude: -7.170359,
          longitude: -103.168995,
        },
        {
          balanceDollars: 1315.04,
          age: 33,
          eyeColor: "blue",
          firstName: "Rogers",
          lastName: "Ford",
          gender: "male",
          email: "rogersford@diginetic.com",
          latitude: -63.577798,
          longitude: -0.675456,
        },
        {
          balanceDollars: 1855.58,
          age: 38,
          eyeColor: "brown",
          firstName: "Kelly",
          lastName: "Simpson",
          gender: "male",
          email: "kellysimpson@diginetic.com",
          latitude: -6.218272,
          longitude: -97.198928,
        },
        {
          balanceDollars: 1574.11,
          age: 39,
          eyeColor: "brown",
          firstName: "Whitney",
          lastName: "Holt",
          gender: "female",
          email: "whitneyholt@diginetic.com",
          latitude: -1.313761,
          longitude: 109.435756,
        },
        {
          balanceDollars: 2935.66,
          age: 38,
          eyeColor: "brown",
          firstName: "Goldie",
          lastName: "Lopez",
          gender: "female",
          email: "goldielopez@diginetic.com",
          latitude: 52.267298,
          longitude: 145.719877,
        },
        {
          balanceDollars: 2094.23,
          age: 33,
          eyeColor: "green",
          firstName: "Valenzuela",
          lastName: "Morales",
          gender: "male",
          email: "valenzuelamorales@diginetic.com",
          latitude: 21.332013,
          longitude: -89.514579,
        },
        {
          balanceDollars: 1279.33,
          age: 36,
          eyeColor: "blue",
          firstName: "Flossie",
          lastName: "Harrington",
          gender: "female",
          email: "flossieharrington@diginetic.com",
          latitude: 82.714816,
          longitude: -98.863611,
        },
        {
          balanceDollars: 1303.49,
          age: 32,
          eyeColor: "green",
          firstName: "Oneal",
          lastName: "Camacho",
          gender: "male",
          email: "onealcamacho@diginetic.com",
          latitude: -29.347048,
          longitude: 81.005717,
        },
        {
          balanceDollars: 1534.62,
          age: 36,
          eyeColor: "blue",
          firstName: "Rosemarie",
          lastName: "Noel",
          gender: "female",
          email: "rosemarienoel@diginetic.com",
          latitude: 45.463863,
          longitude: -23.229058,
        },
      ],
    },
  },
];
